version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=7.1-apache
    # Build image:tag name
    image: "php:7.1-apache-dev"
    network_mode: "bridge"
    ports:
      - "80:80"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
    container_name: php-7.1
    restart: always
