version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8-apache
    image: "${IMG_TAG}"
    network_mode: "bridge"
    ports:
      - "80:80"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
    container_name: php_8
    restart: always
